### ISSUE TITLE
Wouldnt it be better if we also add Go as a systems programming language?

### ISSUE THREAD

**Issue by rufevean** [ujjwal-kr/system-programming-roadmap#7]

**Comment by ujjwal-kr** [comment]
I consider golang as a cloud systems language. Like I would never attempt to write a firmware or OS with it. It is great for backend systems. But isn't close to bare metal as the other languages mentioned in the list (could add ziglang btw.

With that said, I have still seen malwares being written in go so maybe I will mention in the malwares part.
